export enum EHashAlgorithms {
  SHA256 = 'sha256',
  SHA512 = 'sha512'
}

export enum EError {
  // NO_ERROR = 'NO_ERROR',
  // CERTIFICATE_DATA_MISSING = 'CERTIFICATE_DATA_MISSING',
  // CERTIFICATE_ID_CANNOT_BE_FOUND = 'CERTIFICATE_ID_CANNOT_BE_FOUND',
  // CERTIFICATE_ANCHORED_BY_NOT_AUTHORIZED_DEVICE = 'CERTIFICATE_ANCHORED_BY_NOT_AUTHORIZED_DEVICE',
  // VERIFICATION_FAILED_EMPTY_RESPONSE = 'VERIFICATION_FAILED_EMPTY_RESPONSE',
  // VERIFICATION_FAILED_MISSING_SEAL_IN_RESPONSE = 'VERIFICATION_FAILED_MISSING_SEAL_IN_RESPONSE',
  // VERIFICATION_FAILED = 'VERIFICATION_FAILED',
  // VERIFICATION_CURRENTLY_UNAVAILABLE = 'VERIFICATION_CURRENTLY_UNAVAILABLE',
  // URL_PARAMS_CORRUPT = 'URL_PARAMS_CORRUPT',
  // LOCATION_MALFORMED = 'LOCATION_MALFORMED',
  // MANDATORY_FIELD_MISSING = 'MANDATORY_FIELD_MISSING',
  // FILLING_FORM_WITH_PARAMS_FAILED = 'FILLING_FORM_WITH_PARAMS_FAILED',
  // JSON_PARSE_FAILED = 'JSON_PARSE_FAILED',
   JSON_MALFORMED = 'JSON_MALFORMED',
  // CANNOT_ACCESS_FORM_FIELD = 'CANNOT_ACCESS_FORM_FIELD',
  // MISSING_PROPERTY_IN_UBRICH_VERIFICATION_INSTANCIATION = 'MISSING_PROPERTY_IN_UBRICH_VERIFICATION_INSTANCIATION',
  // ELEMENT_FOR_WIDGET_SELECTOR_NOT_FOUND = 'ELEMENT_FOR_WIDGET_SELECTOR_NOT_FOUND',
  // MISSING_PARAM_IDS = 'MISSING_PARAM_IDS',
  // PARAM_ID_MAPPING_MISSMATCH = 'PARAM_ID_MAPPING_MISSMATCH',
  // MISSING_ACCESS_TOKEN = 'MISSING_ACCESS_TOKEN',
  // UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}

export interface IUbirchError {
  message: string;
  code: EError;
}
